steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us.gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}",
        "--cache-from=us.gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us.gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}"
      ]

  - name: "us.gcr.io/${PROJECT_ID}/${REPO_NAME}/${BRANCH_NAME}"
    entrypoint: "bash"
    args:
      - "-c"
      - |
          command -v gke-gcloud-auth-plugin

          gcloud container clusters get-credentials raio --zone us-central1-c --project ${PROJECT_ID} || echo "Cluster não disponível. Ignorando para teste."

          cd infra/test

          terraform init -input=false
          terraform apply -auto-approve -input=false \
            -var="project_id=${PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY